# Generated by Django 4.1.5 on 2023-01-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('unique_code', models.CharField(max_length=100, unique=True)),
                ('size', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30')], max_length=100)),
                ('quality', models.CharField(choices=[('high', 'high'), ('low', 'low'), ('medium', 'medium')], max_length=100)),
            ],
            options={
                'db_table': 'prod',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapi.productmodel')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='ColourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('black', 'black')], max_length=100)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapi.productmodel')),
            ],
            options={
                'db_table': 'color',
            },
        ),
    ]
