# Generated by Django 4.1.5 on 2023-01-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0005_alter_colourmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_f', to='testapi.productmodel'),
        ),
    ]
