# Generated by Django 4.1.5 on 2023-01-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0006_alter_imagemodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapi.productmodel'),
        ),
    ]
